#!/bin/bash

set -e
set -o pipefail

if [[ -z "${TRAVIS_BUILD_DIR}" ]]; then
    START_CWD="${PWD}"
else
    START_CWD="${TRAVIS_BUILD_DIR}"
fi

cd "${START_CWD}" || exit 1

mdl -s mdl-rules.rb .

MD_FILES=($(find ./ -type f -iname "*.md"))

for f in "${MD_FILES[@]}"; do
    mdspell --en-us -ran "$f"
done

exit
